#!/bin/sh /etc/rc.common
# Copyright (C) 2014 OpenWrt.org

START=99
STOP=01

ssl_start() {
    /usr/sbin/touchmod /var/ssl/asterisk.key 0600 asterisk asterisk
    /usr/sbin/touchmod /var/ssl/asterisk.crt 0600 asterisk asterisk

    /usr/bin/openssl rsa -in /etc/ssl/private/server.key -passin file:/sys/class/dmi/id/product_uuid -out /var/ssl/asterisk.key &>/dev/null
    cat /etc/ssl/private/server.crt > /var/ssl/asterisk.crt
}

gen_conf() {
    /usr/bin/sudo -u http -g yunapbx /usr/bin/php-cli /www/generator/confbridge.conf.php
    /usr/bin/sudo -u http -g yunapbx /usr/bin/php-cli /www/generator/dongle.conf.php
    /usr/bin/sudo -u http -g yunapbx /usr/bin/php-cli /www/generator/extensions.conf.php
    /usr/bin/sudo -u http -g yunapbx /usr/bin/php-cli /www/generator/musiconhold.conf.php
    /usr/bin/sudo -u http -g yunapbx /usr/bin/php-cli /www/generator/pjsip.conf.php
    /usr/bin/sudo -u http -g yunapbx /usr/bin/php-cli /www/generator/queues.conf.php
    /usr/bin/sudo -u http -g yunapbx /usr/bin/php-cli /www/generator/sip.conf.php
    /usr/bin/sudo -u http -g yunapbx /usr/bin/php-cli /www/generator/voicemail.conf.php
}

ssl_stop() {
    rm /var/ssl/asterisk.key
    rm /var/ssl/asterisk.crt
}

start() {
    mkdir -p /var/log/asterisk
    mkdir -p /usr/lib/asterisk/keys
    mkdir -p /var/run/asterisk

    mkdir -m 0770 -p /data/moh
    mkdir -m 0770 -p /data/monitor
    mkdir -m 0770 -p /var/yunapbx

    chown -R asterisk:asterisk /var/log/asterisk
    chown -R asterisk:asterisk /usr/lib/asterisk
    chown -R asterisk:asterisk /var/run/asterisk

    chown -R asterisk:yunapbx /data/moh
    chown -R asterisk:yunapbx /data/monitor
    chown -R http:yunapbx /var/yunapbx

    chmod 0777 /var/lock

    ssl_start
    gen_conf

    service_start /usr/sbin/asterisk
}

stop() {
    service_stop /usr/sbin/asterisk
    ssl_stop
}

reload() {
    ssl_start
    /usr/sbin/asterisk -rx 'core reload'
}
