#!/bin/sh /etc/rc.common
# Copyright (C) 2009-2010 OpenWrt.org

START=60
STOP=80

SERVICE_USE_PID=1

HAPROXY_BIN="/usr/sbin/haproxy"
HAPROXY_CONFIG="/etc/haproxy.cfg"
HAPROXY_PID="/var/run/haproxy.pid"

ssl_start() {
    /usr/sbin/touchmod /var/ssl/haproxy.crt 0600 haproxy haproxy

    /usr/bin/openssl rsa -in /etc/ssl/private/server.key -passin file:/sys/class/dmi/id/product_uuid -out /var/ssl/haproxy.crt &>/dev/null
    cat /etc/ssl/private/server.crt >> /var/ssl/haproxy.crt
}

ssl_stop() {
    rm /var/ssl/haproxy.crt
}

start() {
    ssl_start
    service_start $HAPROXY_BIN -q -D -f "$HAPROXY_CONFIG" -p "$HAPROXY_PID"
}

stop() {
    service_stop $HAPROXY_BIN
    ssl_stop
}

reload() {
    ssl_start
    $HAPROXY_BIN -D -q -f $HAPROXY_CONFIG -p $HAPROXY_PID -sf $(cat $HAPROXY_PID | tr "\n" " ")
}
