#!/bin/sh /etc/rc.common
# Copyright (C) 2010-2011 OpenWrt.org

START=50
STOP=10

USE_PROCD=1

start_service() {
    mkdir -m 0700 -p /data/mysql
    mkdir -m 0770 -p /var/run/mysql

    chown -R mariadb:mariadb /data/mysql
    chown -R mariadb:yunapbx /var/run/mysql

    if [ ! -f "/data/mysql/mysql/tables_priv.MYD" ]; then
        /usr/bin/mysql_install_db --force
    fi

    procd_open_instance
    procd_set_param command /usr/bin/mysqld
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}
