#!/bin/sh /etc/rc.common
# Copyright (C) 2008-2011 OpenWrt.org

START=60

USE_PROCD=1
PROG=/usr/sbin/zabbix_agentd
CONFIG=/etc/zabbix_agentd.conf

ssl_start() {
    /usr/sbin/touchmod /var/ssl/zabbix.key 0600 zabbix zabbix
    /usr/sbin/touchmod /var/ssl/zabbix.crt 0600 zabbix zabbix

    /usr/bin/openssl rsa -in /etc/ssl/private/server.key -passin file:/sys/class/dmi/id/product_uuid -out /var/ssl/zabbix.key &>/dev/null
    cat /etc/ssl/private/server.crt > /var/ssl/zabbix.crt
}

start_service() {
    mkdir -p /var/run/zabbix
    chown -R zabbix:zabbix /var/run/zabbix

    find -L /sys/class/hwmon/ -maxdepth 3 -name 'temp*_input' -exec ln -sf {} /tmp/cpu_temp \; 2>/dev/null
    
    ssl_start
    
    procd_open_instance
    procd_set_param command ${PROG} -c ${CONFIG} -f
    procd_set_param respawn
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}
