#!/bin/sh /etc/rc.common
# Copyright (C) 2014 OpenWrt.org

START=99
STOP=01

ssl_start() {
    /usr/sbin/touchmod /var/ssl/asterisk.key 0600 asterisk asterisk
    /usr/sbin/touchmod /var/ssl/asterisk.crt 0600 asterisk asterisk

    /usr/bin/openssl rsa -in /etc/ssl/private/server.key -passin file:/sys/class/dmi/id/product_uuid -out /var/ssl/asterisk.key &>/dev/null
    cat /etc/ssl/private/server.crt > /var/ssl/asterisk.crt
}

ssl_stop() {
    rm /var/ssl/asterisk.key
    rm /var/ssl/asterisk.crt
}

start() {
    mkdir -p /var/log/asterisk
    mkdir -p /usr/lib/asterisk/keys
    mkdir -p /var/run/asterisk    

    chown -R asterisk:asterisk /var/log/asterisk
    chown -R asterisk:asterisk /usr/lib/asterisk
    chown -R asterisk:asterisk /var/run/asterisk

    ssl_start
    service_start /usr/sbin/asterisk
}

stop() {
    service_stop /usr/sbin/asterisk
    ssl_stop
}

reload() {
    ssl_start
    /usr/sbin/asterisk -rx 'core reload'
}
