#!/bin/sh /etc/rc.common
# Copyright (C) 2014 OpenWrt.org

START=99

start() {
       mkdir -p /var/log/asterisk
       mkdir -p /var/spool/asterisk

       chown -R asterisk:asterisk /var/log/asterisk
       chown -R asterisk:asterisk /var/spool/asterisk
       chown -R asterisk:asterisk /usr/lib/asterisk

       mkdir -m 0777 -p /tmp/ssl

       /usr/sbin/touchmod /tmp/ssl/asterisk.key 0600 asterisk asterisk
       /usr/sbin/touchmod /tmp/ssl/asterisk.crt 0600 asterisk asterisk

       cat /etc/ssl/private/server.key > /tmp/ssl/asterisk.key
       cat /etc/ssl/private/server.crt > /tmp/ssl/asterisk.crt

       service_start /usr/sbin/asterisk
}

stop() {
       /usr/sbin/asterisk -rx 'core stop now'
}

reload() {
       /usr/sbin/asterisk -rx 'core reload'
}
