#!/bin/sh /etc/rc.common
# Copyright (C) 2009-2010 OpenWrt.org

START=99
STOP=80

SERVICE_USE_PID=1

HAPROXY_BIN="/usr/sbin/haproxy"
HAPROXY_CONFIG="/etc/haproxy.cfg"
HAPROXY_PID="/var/run/haproxy.pid"

start() {
        mkdir -m 0777 -p /var/ssl

        /usr/sbin/touchmod /var/ssl/haproxy.crt 0600 haproxy haproxy

        /usr/bin/openssl rsa -in /etc/ssl/private/server.key -passin file:/sys/class/dmi/id/product_uuid > /var/ssl/haproxy.crt
        cat /etc/ssl/private/server.crt >> /var/ssl/haproxy.crt

        service_start $HAPROXY_BIN -q -D -f "$HAPROXY_CONFIG" -p "$HAPROXY_PID"
}

stop() {
        kill -9 $(cat $HAPROXY_PID | tr "\n" " ")
        service_stop $HAPROXY_BIN
}

reload() {
        $HAPROXY_BIN -D -q -f $HAPROXY_CONFIG -p $HAPROXY_PID -sf $(cat $HAPROXY_PID | tr "\n" " ")
        #$HAPROXY_BIN -D -q -f $HAPROXY_CONFIG -p $HAPROXY_PID -sf $(cat $HAPROXY_PID)
}
