#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

SERVICE_USE_PID=1

START=50

start() {
        chown -R http:http /www
        service_start /usr/sbin/lighttpd -f /etc/lighttpd/lighttpd.conf
}

stop() {
        service_stop /usr/sbin/lighttpd
}
