#!/bin/sh /etc/rc.common
# Copyright (C) 2010-2011 OpenWrt.org

START=95
STOP=10

SERVICE_DAEMONIZE=1
SERVICE_STOP_TIME=9

error() {
	echo "${initscript}:" "$@" 1>&2
}

start() {
	if [ ! -d "/data/mysql" ]; then
		mkdir -p "/data/mysql"
        chown mysql:mysql /data/mysql
        chmod 0700 /data/mysql
	fi
	if [ ! -f "/data/mysql/mysql/tables_priv.MYD" ]; then
		/usr/bin/mysql_install_db --force
	fi
	service_start /usr/bin/mysqld
}

stop() {
	service_stop /usr/bin/mysqld
}
