#!/bin/sh /etc/rc.common
# Copyright (C) 2010-2011 OpenWrt.org

START=95
STOP=10

SERVICE_DAEMONIZE=1
SERVICE_WRITE_PID=1
SERVICE_STOP_TIME=9

error() {
	echo "${initscript}:" "$@" 1>&2
}

start() {
	local datadir=$(sed -n -e "s/^[[:space:]]*datadir[[:space:]]*=[[:space:]]*[\"']\?\([^\"']*\)[\"']\?/\1/p" /etc/my.cnf)
	if [ ! -d "$datadir" ]; then
		mkdir -p "$datadir"
	fi
	if [ ! -f "$datadir/mysql/tables_priv.MYD" ]; then
		/usr/bin/mysql_install_db --force
	fi
	service_start /usr/bin/mysqld
}

stop() {
	service_stop /usr/bin/mysqld
}
