#!/bin/sh /etc/rc.common
# Copyright (C) 2011-2016 OpenWrt.org

START=99

USE_PROCD=1

BIN=/usr/bin/prosodyctl
LOG_D=/var/log/prosody
RUN_D=/var/run/prosody
PID_F=$RUN_D/prosody.pid
RUN_USER=prosody
RUN_GROUP=prosody

start_service() {
    procd_open_instance
    procd_set_param command "$BIN" start
    procd_set_param file /etc/prosody/prosody.cfg.lua
    procd_close_instance
}

stop_service() {
    ${BIN} stop
}

reload_service() {
    ${BIN} reload
}
