#!/bin/sh /etc/rc.common

start() {
    /usr/bin/php-cli /usr/share/yunapbx/db/install_upgrade_db.php
    
    /usr/bin/php-cli /www/generator/dongle.conf.php
    /usr/bin/php-cli /www/generator/extensions.conf.php
    /usr/bin/php-cli /www/generator/features.conf.php
    /usr/bin/php-cli /www/generator/meetme.conf.php
    /usr/bin/php-cli /www/generator/musiconhold.conf.php
    /usr/bin/php-cli /www/generator/queues.conf.php
    /usr/bin/php-cli /www/generator/sip.conf.php
    /usr/bin/php-cli /www/generator/voicemail.conf.php

    rm /etc/rc.d/S96firstboot
    
}
