#!/bin/sh /etc/rc.common
# Copyright (C) 2009-2010 OpenWrt.org

START=55

SSL_PATH="/etc/ssl/private"
KEY_PASS="file:/sys/class/dmi/id/product_uuid"

start() {
    if [ ! -f "$SSL_PATH/server.key" ] || [ ! -f "$SSL_PATH/server.crt" ]; then
        mkdir -m 0700 -p "$SSL_PATH"

        /usr/sbin/touchmod "$SSL_PATH/server.key" 0600 root root
        /usr/sbin/touchmod "$SSL_PATH/server.csr" 0600 root root
        /usr/sbin/touchmod "$SSL_PATH/server.crt" 0600 root root

        /usr/bin/openssl genrsa -aes256 -passout "$KEY_PASS" 2048 > "$SSL_PATH/server.key"
        /usr/bin/openssl req -new -key "$SSL_PATH/server.key" -passin "$KEY_PASS" -days 3650 -sha256 -subj "/CN=`cat /proc/sys/kernel/hostname`" > "$SSL_PATH/server.csr"
        /usr/bin/openssl x509 -req -in "$SSL_PATH/server.csr" -signkey "$SSL_PATH/server.key" -sha256 -passin "$KEY_PASS" > "$SSL_PATH/server.crt"
    fi

    mkdir -m 0777 -p /var/ssl

    mkdir -m 0770 -p /data/moh
    mkdir -m 0770 -p /data/monitor
    mkdir -m 0770 -p /var/yunapbx

    chown -R asterisk:yunapbx /data/moh
    chown -R asterisk:yunapbx /data/monitor
    chown -R asterisk:yunapbx /var/yunapbx

    /usr/sbin/touchmod /var/yunapbx/dongle.conf 0660 asterisk yunapbx
    /usr/sbin/touchmod /var/yunapbx/extensions.conf 0660 asterisk yunapbx
    /usr/sbin/touchmod /var/yunapbx/features.conf 0660 asterisk yunapbx
    /usr/sbin/touchmod /var/yunapbx/meetme.conf 0660 asterisk yunapbx
    /usr/sbin/touchmod /var/yunapbx/musiconhold.conf 0660 asterisk yunapbx
    /usr/sbin/touchmod /var/yunapbx/queues.conf 0660 asterisk yunapbx
    /usr/sbin/touchmod /var/yunapbx/sip.conf 0660 asterisk yunapbx
    /usr/sbin/touchmod /var/yunapbx/voicemail.conf 0660 asterisk yunapbx

    #/usr/bin/php-cli /www/generator/dongle.conf.php
    #/usr/bin/php-cli /www/generator/extensions.conf.php
    #/usr/bin/php-cli /www/generator/features.conf.php
    #/usr/bin/php-cli /www/generator/meetme.conf.php
    #/usr/bin/php-cli /www/generator/musiconhold.conf.php
    #/usr/bin/php-cli /www/generator/queues.conf.php
    #/usr/bin/php-cli /www/generator/sip.conf.php
    #/usr/bin/php-cli /www/generator/voicemail.conf.php

}
